### ISSUE TITLE
Model file not found

### ISSUE THREAD

**Issue by robotiste** [DavidFernandezChaves/detectron2_ros#7]
It is unable to find the "model_final_f10217.pkl" file 

```
process[detectron2_ros-1]: started with pid [14640]
[WARN] [1632167722.433477]: Initializing
[INFO] [1632167722.442250]: [Detectron2] ~config: /home/vikas/detectron_ros/src/detectron2_ros/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml
[INFO] [1632167722.470800]: [Detectron2] ~detection_threshold: 0.5
[INFO] [1632167722.473040]: [Detectron2] ~model: detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
Traceback (most recent call last):
  File "/home/vikas/detectron_ros/src/detectron2_ros/src/detectron2_ros", line 158, in <module>
    main(sys.argv)
  File "/home/vikas/detectron_ros/src/detectron2_ros/src/detectron2_ros", line 154, in main
    node = Detectron2node()
  File "/home/vikas/detectron_ros/src/detectron2_ros/src/detectron2_ros", line 34, in __init__
    self.predictor = DefaultPredictor(self.cfg)
  File "/home/vikas/.virtualenvs/detectron2_ros/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 188, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/vikas/.virtualenvs/detectron2_ros/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 141, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl not found!
[detectron2_ros-1] process has died [pid 14640, exit code 1, cmd /home/vikas/detectron_ros/src/detectron2_ros/src/detectron2_ros __name:=detectron2_ros __log:=/home/vikas/.ros/log/a2aa41ea-1a4c-11ec-8c3f-2d667ddb57ab/detectron2_ros-1.log].
log file: /home/vikas/.ros/log/a2aa41ea-1a4c-11ec-8c3f-2d667ddb57ab/detectron2_ros-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

**Comment by DavidFernandezChaves** [comment]
This is because you are not running it inside the environment properly, since it is using python 3.8. This port is intended to be used in ROS with python2. Please follow the instructions for use.

**Comment by Hz19970829** [comment]
I have the same problem, do you have a solution?

**Comment by Hz19970829** [comment]
Which version uses python 3.6 or 3.8? Not sure how to use python3 and python2 at the same time, can you help me?
My workon environment is python 3.6, ros python 2.7

**Comment by josematez** [comment]
Hello, you can download the model "model_final_f10217.pkl" from [here](https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl). Then, drag it into the folder where the code expects to find the model.

**Comment by Hz19970829** [comment]
thanks for your answer
